version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: vac_nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443

    react:
        build: ./react-app
        container_name: vac_react
        expose:
            - "5000"
        ports:
            - 5000:5000
